In [1]:
import numpy as np
import pandas as pd


In [4]:
np.random.seed(23)

None


In [35]:
mean_vec1 = np.array([1,1,1])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1

mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])

df1['target'] = 0

df = pd.concat([df,df1],axis = 0)

df = df.sample(40)

In [36]:
df

feature1  feature2  feature3  target
14  0.286350 -0.155203  1.960595       1
10  0.817614 -0.194328 -0.135024       1
13  0.607177  1.245376 -0.218714       0
15  0.234178  0.686935  0.425540       1
15 -1.028595  0.467326  1.002633       0
19  0.582606 -0.013034  0.512415       0
11  1.345650  0.505524  0.206121       0
1   0.139554  1.198278  1.934223       0
3   0.007991  2.939454  1.483802       0
1   0.786271 -0.383103  1.352240       1
3  -0.610882  1.187585  0.892404       1
17  0.924466  1.643999 -0.024643       1
18  0.561363  0.937107  0.747472       1
9   1.227240 -0.652904 -0.190392       0
10  3.539272  0.944246  1.531737       0
14  1.740616 -0.100171  0.838972       0
12  1.636428  0.355312  1.540431       1
7   1.426356  0.589672  1.207379       1
8   1.399795  1.180892  0.845678       1
17 -0.342756  1.321036  1.692500       0
11  0.954825  1.064722  0.851376       1
0   1.875443  1.563703  1.140788       1
5  -1.014665  2.752513 -0.209350       1
2   1.665336 -0.688001  2.203646       1
6  -0.615849  1.191877  0.592985       1
19  0.667001  0.795522  2.122827       1
13  0.894028  0.690214  1.000777       1
7  -0.037357 -0.881713  1.317351       0
4   0.570252  0.568752  1.600203       0
0   0.794216  0.285419  2.818548       0
16  2.345596  0.662724  0.629874       0
5   0.846728  1.494321  0.057979       0
9   2.659491  0.296691  0.079341       1
4   0.728621  0.740146  1.974879       1
6   2.471778 -0.100730  1.571352       0
18  2.093337  0.797748  1.617695       0
12  0.600147  0.599503 -0.581823       0
8   1.602046  0.729564  1.386507       0
2   0.433420  0.811843  1.285793       0
16  1.257001 -0.336064  0.212625       1

In [37]:
df.head()

feature1  feature2  feature3  target
14  0.286350 -0.155203  1.960595       1
10  0.817614 -0.194328 -0.135024       1
13  0.607177  1.245376 -0.218714       0
15  0.234178  0.686935  0.425540       1
15 -1.028595  0.467326  1.002633       0

In [38]:
# we want to convert this 3d data to 2d
# step 1 => apply standard scalling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df.iloc[:,:3]=scaler.fit_transform(df.iloc[:,:3])

In [39]:
# step 2 finding covariance matrix
cov_matrix=df.cov()
cov_matrix

feature1  feature2  feature3    target
feature1  1.025641 -0.295219  0.075665 -0.039690
feature2 -0.295219  1.025641 -0.125512  0.017524
feature3  0.075665 -0.125512  1.025641 -0.027902
target   -0.039690  0.017524 -0.027902  0.256410

In [40]:
# step 3 => finding eigenvalues and eigenvectors
eigen_values,eigen_vectors = np.linalg.eig(cov_matrix)
eigen_values,eigen_vectors

(array([1.38054014, 0.97275098, 0.72642725, 0.25361496]),
 array([[ 0.6406416 , -0.35970026, -0.67662982,  0.04864304],
        [-0.66803956,  0.17213715, -0.72394118,  0.00105925],
        [ 0.37617315,  0.91697901, -0.1290423 ,  0.03148549],
        [-0.04237034, -0.01157642,  0.03780667,  0.99831929]]))

In [41]:
eigen_vectors.shape

(4, 4)

In [42]:
# we want 2d data so let's take first 2 eigen vectors
pc = eigen_vectors[:2,:3]
pc

array([[ 0.6406416 , -0.35970026, -0.67662982],
       [-0.66803956,  0.17213715, -0.72394118]])

In [43]:
transformed_df = np.dot(df.iloc[:,:3],pc.T)
new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2'])
new_df['target'] = df['target'].values
new_df.head()

PC1       PC2  target
0 -0.877507 -0.652277       1
1  1.290186  0.899247       1
2  0.578314  1.429549       0
3  0.029082  0.974547       1
4 -1.201356  1.266103       0